# -*- coding: utf-8 -*-
"""Professional-Profile-Parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqRP-ymzKbrkrR-I45Nc5FsvrlHOSxQf
"""

!pip install docx2txt
import docx2txt

job_description = docx2txt.process('/content/artificial-intelligence-v1.docx')
resume = docx2txt.process('/content/Resume_suvro2.docx')

print(resume)

content = [job_description, resume]

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
matrix = cv.fit_transform(content)
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(matrix)
print(similarity_matrix)

print('Resume matches by : '+ str(round(similarity_matrix[1][0]* 100))+ '%')

CV = docx2txt.process('/content/CV_suvro.docx')

content2 = [job_description, CV]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
matrix = cv.fit_transform(content2)
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(matrix)
print(similarity_matrix)
print('CV matches by : '+ str(round(similarity_matrix[1][0]* 100))+ '%')

!pip install -U spacy
!pip install spacy_transformers

import spacy
from spacy.tokens import DocBin
from tqdm import tqdm
import json

cv_data = json.load(open('/content/train_data.json', 'r'))

len(cv_data)

cv_data[0]

